export type CountryCode = {
  name: string;
  iso2: string;
  dialCode: string;
  flag: string;
};

// Dial codes, not an exhaustive ISO-3166 list, but covers the countries a
// dive center's international clientele will actually select in practice.
export const COUNTRY_CODES: CountryCode[] = [
  { name: "Philippines", iso2: "PH", dialCode: "+63", flag: "🇵🇭" },
  { name: "United States", iso2: "US", dialCode: "+1", flag: "🇺🇸" },
  { name: "Canada", iso2: "CA", dialCode: "+1", flag: "🇨🇦" },
  { name: "United Kingdom", iso2: "GB", dialCode: "+44", flag: "🇬🇧" },
  { name: "Australia", iso2: "AU", dialCode: "+61", flag: "🇦🇺" },
  { name: "New Zealand", iso2: "NZ", dialCode: "+64", flag: "🇳🇿" },
  { name: "Germany", iso2: "DE", dialCode: "+49", flag: "🇩🇪" },
  { name: "France", iso2: "FR", dialCode: "+33", flag: "🇫🇷" },
  { name: "Italy", iso2: "IT", dialCode: "+39", flag: "🇮🇹" },
  { name: "Spain", iso2: "ES", dialCode: "+34", flag: "🇪🇸" },
  { name: "Portugal", iso2: "PT", dialCode: "+351", flag: "🇵🇹" },
  { name: "Netherlands", iso2: "NL", dialCode: "+31", flag: "🇳🇱" },
  { name: "Belgium", iso2: "BE", dialCode: "+32", flag: "🇧🇪" },
  { name: "Switzerland", iso2: "CH", dialCode: "+41", flag: "🇨🇭" },
  { name: "Austria", iso2: "AT", dialCode: "+43", flag: "🇦🇹" },
  { name: "Sweden", iso2: "SE", dialCode: "+46", flag: "🇸🇪" },
  { name: "Norway", iso2: "NO", dialCode: "+47", flag: "🇳🇴" },
  { name: "Denmark", iso2: "DK", dialCode: "+45", flag: "🇩🇰" },
  { name: "Finland", iso2: "FI", dialCode: "+358", flag: "🇫🇮" },
  { name: "Ireland", iso2: "IE", dialCode: "+353", flag: "🇮🇪" },
  { name: "Poland", iso2: "PL", dialCode: "+48", flag: "🇵🇱" },
  { name: "Czech Republic", iso2: "CZ", dialCode: "+420", flag: "🇨🇿" },
  { name: "Russia", iso2: "RU", dialCode: "+7", flag: "🇷🇺" },
  { name: "Ukraine", iso2: "UA", dialCode: "+380", flag: "🇺🇦" },
  { name: "Greece", iso2: "GR", dialCode: "+30", flag: "🇬🇷" },
  { name: "Turkey", iso2: "TR", dialCode: "+90", flag: "🇹🇷" },
  { name: "Israel", iso2: "IL", dialCode: "+972", flag: "🇮🇱" },
  { name: "United Arab Emirates", iso2: "AE", dialCode: "+971", flag: "🇦🇪" },
  { name: "Saudi Arabia", iso2: "SA", dialCode: "+966", flag: "🇸🇦" },
  { name: "Qatar", iso2: "QA", dialCode: "+974", flag: "🇶🇦" },
  { name: "South Africa", iso2: "ZA", dialCode: "+27", flag: "🇿🇦" },
  { name: "Egypt", iso2: "EG", dialCode: "+20", flag: "🇪🇬" },
  { name: "India", iso2: "IN", dialCode: "+91", flag: "🇮🇳" },
  { name: "Pakistan", iso2: "PK", dialCode: "+92", flag: "🇵🇰" },
  { name: "Bangladesh", iso2: "BD", dialCode: "+880", flag: "🇧🇩" },
  { name: "Sri Lanka", iso2: "LK", dialCode: "+94", flag: "🇱🇰" },
  { name: "Nepal", iso2: "NP", dialCode: "+977", flag: "🇳🇵" },
  { name: "China", iso2: "CN", dialCode: "+86", flag: "🇨🇳" },
  { name: "Hong Kong", iso2: "HK", dialCode: "+852", flag: "🇭🇰" },
  { name: "Taiwan", iso2: "TW", dialCode: "+886", flag: "🇹🇼" },
  { name: "Japan", iso2: "JP", dialCode: "+81", flag: "🇯🇵" },
  { name: "South Korea", iso2: "KR", dialCode: "+82", flag: "🇰🇷" },
  { name: "Singapore", iso2: "SG", dialCode: "+65", flag: "🇸🇬" },
  { name: "Malaysia", iso2: "MY", dialCode: "+60", flag: "🇲🇾" },
  { name: "Indonesia", iso2: "ID", dialCode: "+62", flag: "🇮🇩" },
  { name: "Thailand", iso2: "TH", dialCode: "+66", flag: "🇹🇭" },
  { name: "Vietnam", iso2: "VN", dialCode: "+84", flag: "🇻🇳" },
  { name: "Cambodia", iso2: "KH", dialCode: "+855", flag: "🇰🇭" },
  { name: "Myanmar", iso2: "MM", dialCode: "+95", flag: "🇲🇲" },
  { name: "Laos", iso2: "LA", dialCode: "+856", flag: "🇱🇦" },
  { name: "Brunei", iso2: "BN", dialCode: "+673", flag: "🇧🇳" },
  { name: "Brazil", iso2: "BR", dialCode: "+55", flag: "🇧🇷" },
  { name: "Argentina", iso2: "AR", dialCode: "+54", flag: "🇦🇷" },
  { name: "Chile", iso2: "CL", dialCode: "+56", flag: "🇨🇱" },
  { name: "Colombia", iso2: "CO", dialCode: "+57", flag: "🇨🇴" },
  { name: "Mexico", iso2: "MX", dialCode: "+52", flag: "🇲🇽" },
  { name: "Peru", iso2: "PE", dialCode: "+51", flag: "🇵🇪" },
  { name: "Ecuador", iso2: "EC", dialCode: "+593", flag: "🇪🇨" },
  { name: "Venezuela", iso2: "VE", dialCode: "+58", flag: "🇻🇪" },
  { name: "Other", iso2: "XX", dialCode: "+", flag: "🌐" },
];

export const DEFAULT_COUNTRY_DIAL_CODE = "+63";
