// Email clients strip <style> blocks and ignore Tailwind's compiled
// stylesheet entirely (it's never included in the email itself), so this
// mirrors InvoicePanel.tsx's print layout but with genuinely inline styles
// instead of class names — the two intentionally look similar, not shared,
// since the constraints (email-safe HTML vs. a real browser print view)
// are different enough that trying to share one component isn't worth it.

function peso(n: number): string {
  return `₱${Math.round(n).toLocaleString()}`;
}

function num(v: unknown): number {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

function fmtDateTime(iso: string): string {
  const d = new Date(iso);
  if (isNaN(d.getTime())) return "—";
  return (
    d.toLocaleDateString("en-PH", { month: "short", day: "numeric", year: "numeric" }) +
    " " +
    d.toLocaleTimeString("en-PH", { hour: "2-digit", minute: "2-digit" })
  );
}

export function buildInvoiceEmailHtml(params: {
  diveCenterName: string;
  snapshot: Record<string, unknown>;
}): string {
  const { diveCenterName, snapshot } = params;
  const activities = (snapshot.activities as Record<string, unknown>[] | undefined) ?? [];
  const payment = (snapshot.payment as Record<string, unknown> | undefined) ?? {};
  const grandTotal = num(snapshot.grand_total);
  const discount = num(snapshot.discount);
  const diverName = typeof snapshot.diver_name === "string" ? snapshot.diver_name : "Diver";
  const closedAt = typeof snapshot.closed_at === "string" ? snapshot.closed_at : new Date().toISOString();
  const closedBy = typeof snapshot.closed_by === "string" ? snapshot.closed_by : "—";

  const rows = activities
    .map(
      (a) => `
        <tr>
          <td style="padding:8px;border-bottom:1px solid #eee;font-size:13px;">${String(a.date ?? "—")}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;font-size:13px;">${String(a.dive_site ?? "—")}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;font-size:13px;text-align:right;">${peso(
            num(a.dive_rate) + num(a.fuel_surcharge) + num(a.marine_tax) + num(a.shark_fee) + num(a.nitrox_fee) + num(a.fifteen_l_fee) + num(a.equipment_rental) + num(a.addons),
          )}</td>
        </tr>`,
    )
    .join("");

  const paymentRows = [
    discount > 0 ? ["Discount", `− ${peso(discount)}`] : null,
    num(payment.cash_amount) > 0 ? ["Cash", peso(num(payment.cash_amount))] : null,
    num(payment.card_amount) > 0 ? ["Card", peso(num(payment.card_amount))] : null,
    num(payment.online_amount) > 0 ? ["Online", peso(num(payment.online_amount))] : null,
  ]
    .filter((r): r is [string, string] => r !== null)
    .map(
      ([label, value]) => `
        <tr>
          <td style="padding:6px 10px;font-size:13px;">${label}</td>
          <td style="padding:6px 10px;font-size:13px;text-align:right;">${value}</td>
        </tr>`,
    )
    .join("");

  return `
<div style="font-family:Arial,Helvetica,sans-serif;max-width:600px;margin:0 auto;color:#1a1a2e;">
  <div style="border-bottom:2px solid #1a1a2e;padding-bottom:16px;margin-bottom:20px;">
    <div style="font-size:22px;font-weight:bold;">${diveCenterName}</div>
    <div style="font-size:13px;color:#888;margin-top:4px;">Invoice for ${diverName}</div>
  </div>

  <p style="font-size:14px;">Hi ${diverName},</p>
  <p style="font-size:14px;">Thanks for diving with us! Here's your invoice, closed on ${fmtDateTime(closedAt)} by ${closedBy}.</p>

  <table style="width:100%;border-collapse:collapse;margin:16px 0;">
    <thead>
      <tr style="background:#f5f5f5;text-align:left;">
        <th style="padding:8px;font-size:11px;text-transform:uppercase;color:#888;">Date</th>
        <th style="padding:8px;font-size:11px;text-transform:uppercase;color:#888;">Activity</th>
        <th style="padding:8px;font-size:11px;text-transform:uppercase;color:#888;text-align:right;">Amount</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <table style="width:100%;max-width:280px;margin-left:auto;border:1px solid #eee;border-radius:8px;overflow:hidden;">
    <tbody>
      ${paymentRows}
      <tr style="background:#1a1a2e;color:#fff;font-weight:bold;">
        <td style="padding:8px 10px;font-size:14px;">Grand Total</td>
        <td style="padding:8px 10px;font-size:14px;text-align:right;">${peso(grandTotal)}</td>
      </tr>
    </tbody>
  </table>

  <p style="font-size:12px;color:#999;text-align:center;margin-top:28px;border-top:1px solid #eee;padding-top:12px;">
    Generated by AquaDesk &middot; ${diveCenterName}
  </p>
</div>`;
}
